baseURL = 'https://lubbockhamradio.org/'
languageCode = 'en-us'
title = 'Ham Radio Lubbock'
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "" # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "K5CV"


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Who, what, and when all things radio in Lubbock, TX. (Ham/Amateur Radio, GMRS, and anything rf.)"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "Amateur Radio (Ham Radio) and GMRS in Lubbock, Tx. A collection of the people, events, and how to get involved with ham radio, gmrs, or other types of radio in Lubbock, TX and the South Plains."
  keywords = "ham radio Lubbock, amateur radio lubbock, gmrs lubbock"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Lubbock Ham Radio"
    subtitle = "Who, what, and when amateur radio things are happening in lubbock."
    keywords = "Lubbock ham radio, Lubbock amateur radio, Lubbock gmrs radio, Lubbock radio"
    copyright = 'LubbockHamRadio.org'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Lubbock Ham Radio"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [params.footer]
    trademark = true
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
    ]

  # Colors for favicons
  #
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"
